// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/protoCache.proto

package proto

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

type GetCacheItemRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCacheItemRequest) Reset()         { *m = GetCacheItemRequest{} }
func (m *GetCacheItemRequest) String() string { return proto.CompactTextString(m) }
func (*GetCacheItemRequest) ProtoMessage()    {}
func (*GetCacheItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8cdbef44ef82bf, []int{0}
}

func (m *GetCacheItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCacheItemRequest.Unmarshal(m, b)
}
func (m *GetCacheItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCacheItemRequest.Marshal(b, m, deterministic)
}
func (m *GetCacheItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCacheItemRequest.Merge(m, src)
}
func (m *GetCacheItemRequest) XXX_Size() int {
	return xxx_messageInfo_GetCacheItemRequest.Size(m)
}
func (m *GetCacheItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCacheItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetCacheItemRequest proto.InternalMessageInfo

func (m *GetCacheItemRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type GetCacheItemResponse struct {
	Value                []byte   `protobuf:"bytes,1,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetCacheItemResponse) Reset()         { *m = GetCacheItemResponse{} }
func (m *GetCacheItemResponse) String() string { return proto.CompactTextString(m) }
func (*GetCacheItemResponse) ProtoMessage()    {}
func (*GetCacheItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8cdbef44ef82bf, []int{1}
}

func (m *GetCacheItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetCacheItemResponse.Unmarshal(m, b)
}
func (m *GetCacheItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetCacheItemResponse.Marshal(b, m, deterministic)
}
func (m *GetCacheItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetCacheItemResponse.Merge(m, src)
}
func (m *GetCacheItemResponse) XXX_Size() int {
	return xxx_messageInfo_GetCacheItemResponse.Size(m)
}
func (m *GetCacheItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetCacheItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetCacheItemResponse proto.InternalMessageInfo

func (m *GetCacheItemResponse) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetCacheItemRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	Value                []byte   `protobuf:"bytes,2,opt,name=value,proto3" json:"value,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCacheItemRequest) Reset()         { *m = SetCacheItemRequest{} }
func (m *SetCacheItemRequest) String() string { return proto.CompactTextString(m) }
func (*SetCacheItemRequest) ProtoMessage()    {}
func (*SetCacheItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8cdbef44ef82bf, []int{2}
}

func (m *SetCacheItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCacheItemRequest.Unmarshal(m, b)
}
func (m *SetCacheItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCacheItemRequest.Marshal(b, m, deterministic)
}
func (m *SetCacheItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCacheItemRequest.Merge(m, src)
}
func (m *SetCacheItemRequest) XXX_Size() int {
	return xxx_messageInfo_SetCacheItemRequest.Size(m)
}
func (m *SetCacheItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCacheItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetCacheItemRequest proto.InternalMessageInfo

func (m *SetCacheItemRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

func (m *SetCacheItemRequest) GetValue() []byte {
	if m != nil {
		return m.Value
	}
	return nil
}

type SetCacheItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetCacheItemResponse) Reset()         { *m = SetCacheItemResponse{} }
func (m *SetCacheItemResponse) String() string { return proto.CompactTextString(m) }
func (*SetCacheItemResponse) ProtoMessage()    {}
func (*SetCacheItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8cdbef44ef82bf, []int{3}
}

func (m *SetCacheItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetCacheItemResponse.Unmarshal(m, b)
}
func (m *SetCacheItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetCacheItemResponse.Marshal(b, m, deterministic)
}
func (m *SetCacheItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetCacheItemResponse.Merge(m, src)
}
func (m *SetCacheItemResponse) XXX_Size() int {
	return xxx_messageInfo_SetCacheItemResponse.Size(m)
}
func (m *SetCacheItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetCacheItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetCacheItemResponse proto.InternalMessageInfo

type RemoveCacheItemRequest struct {
	Key                  string   `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveCacheItemRequest) Reset()         { *m = RemoveCacheItemRequest{} }
func (m *RemoveCacheItemRequest) String() string { return proto.CompactTextString(m) }
func (*RemoveCacheItemRequest) ProtoMessage()    {}
func (*RemoveCacheItemRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8cdbef44ef82bf, []int{4}
}

func (m *RemoveCacheItemRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveCacheItemRequest.Unmarshal(m, b)
}
func (m *RemoveCacheItemRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveCacheItemRequest.Marshal(b, m, deterministic)
}
func (m *RemoveCacheItemRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveCacheItemRequest.Merge(m, src)
}
func (m *RemoveCacheItemRequest) XXX_Size() int {
	return xxx_messageInfo_RemoveCacheItemRequest.Size(m)
}
func (m *RemoveCacheItemRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveCacheItemRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveCacheItemRequest proto.InternalMessageInfo

func (m *RemoveCacheItemRequest) GetKey() string {
	if m != nil {
		return m.Key
	}
	return ""
}

type RemoveCacheItemResponse struct {
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RemoveCacheItemResponse) Reset()         { *m = RemoveCacheItemResponse{} }
func (m *RemoveCacheItemResponse) String() string { return proto.CompactTextString(m) }
func (*RemoveCacheItemResponse) ProtoMessage()    {}
func (*RemoveCacheItemResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_fa8cdbef44ef82bf, []int{5}
}

func (m *RemoveCacheItemResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RemoveCacheItemResponse.Unmarshal(m, b)
}
func (m *RemoveCacheItemResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RemoveCacheItemResponse.Marshal(b, m, deterministic)
}
func (m *RemoveCacheItemResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RemoveCacheItemResponse.Merge(m, src)
}
func (m *RemoveCacheItemResponse) XXX_Size() int {
	return xxx_messageInfo_RemoveCacheItemResponse.Size(m)
}
func (m *RemoveCacheItemResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RemoveCacheItemResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RemoveCacheItemResponse proto.InternalMessageInfo

func init() {
	proto.RegisterType((*GetCacheItemRequest)(nil), "GetCacheItemRequest")
	proto.RegisterType((*GetCacheItemResponse)(nil), "GetCacheItemResponse")
	proto.RegisterType((*SetCacheItemRequest)(nil), "SetCacheItemRequest")
	proto.RegisterType((*SetCacheItemResponse)(nil), "SetCacheItemResponse")
	proto.RegisterType((*RemoveCacheItemRequest)(nil), "RemoveCacheItemRequest")
	proto.RegisterType((*RemoveCacheItemResponse)(nil), "RemoveCacheItemResponse")
}

func init() {
	proto.RegisterFile("proto/protoCache.proto", fileDescriptor_fa8cdbef44ef82bf)
}

var fileDescriptor_fa8cdbef44ef82bf = []byte{
	// 236 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xe2, 0x12, 0x2b, 0x28, 0xca, 0x2f,
	0xc9, 0xd7, 0x07, 0x93, 0xce, 0x89, 0xc9, 0x19, 0xa9, 0x7a, 0x60, 0xa6, 0x92, 0x3a, 0x97, 0xb0,
	0x7b, 0x6a, 0x09, 0x58, 0xc4, 0xb3, 0x24, 0x35, 0x37, 0x28, 0xb5, 0xb0, 0x34, 0xb5, 0xb8, 0x44,
	0x48, 0x80, 0x8b, 0x39, 0x3b, 0xb5, 0x52, 0x82, 0x51, 0x81, 0x51, 0x83, 0x33, 0x08, 0xc4, 0x54,
	0xd2, 0xe1, 0x12, 0x41, 0x55, 0x58, 0x5c, 0x90, 0x9f, 0x57, 0x9c, 0x2a, 0x24, 0xc2, 0xc5, 0x5a,
	0x96, 0x98, 0x53, 0x9a, 0x0a, 0x56, 0xcb, 0x13, 0x04, 0xe1, 0x28, 0xd9, 0x72, 0x09, 0x07, 0x13,
	0x63, 0x2c, 0x42, 0x3b, 0x13, 0xb2, 0x76, 0x31, 0x2e, 0x91, 0x60, 0x2c, 0x96, 0x29, 0x69, 0x71,
	0x89, 0x05, 0xa5, 0xe6, 0xe6, 0x97, 0xa5, 0x12, 0xe1, 0x60, 0x49, 0x2e, 0x71, 0x0c, 0xb5, 0x10,
	0x63, 0x8c, 0xce, 0x30, 0x72, 0x71, 0x21, 0x42, 0x42, 0xc8, 0x9a, 0x8b, 0x07, 0xd9, 0x6b, 0x42,
	0x22, 0x7a, 0x58, 0x82, 0x44, 0x4a, 0x54, 0x0f, 0xab, 0xff, 0xad, 0xb9, 0x78, 0x82, 0x51, 0x35,
	0x07, 0x63, 0xd5, 0x8c, 0xcd, 0x3f, 0x42, 0x2e, 0x5c, 0xfc, 0x68, 0x6e, 0x14, 0x12, 0xd7, 0xc3,
	0xee, 0x43, 0x29, 0x09, 0x3d, 0x1c, 0xde, 0x71, 0xd2, 0x8a, 0xd2, 0x48, 0xcf, 0x2c, 0xc9, 0x28,
	0x4d, 0xd2, 0x4b, 0xce, 0xcf, 0xd5, 0x4f, 0xcc, 0xce, 0x2f, 0x4a, 0x49, 0x84, 0xc4, 0x74, 0x32,
	0x48, 0x6d, 0x71, 0x6a, 0x51, 0x59, 0x6a, 0x11, 0x44, 0x20, 0x89, 0x0d, 0x4c, 0x19, 0x03, 0x02,
	0x00, 0x00, 0xff, 0xff, 0x5a, 0xdf, 0x15, 0xb7, 0x10, 0x02, 0x00, 0x00,
}
